import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { getUserInfo } from "@/lib/actions/user.actions";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <main className="flex w-full font-inter">
          <Sidebar />

          <div className="flex size-full flex-col">
            <Header />
             <div className='p-8'>
            {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
