

import Header from "@/components/common/header";
import Sidebar from "@/components/layout/side-bar";

import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "E-shopper",
  description: "Generated by E-shopper",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <main className="flex w-full font-inter">
          <Sidebar />

          <div className="flex size-full flex-col">
            <Header />
             <div className='p-8'>
            {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
